# Copyright 2020-present The Material Foundation Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@build_bazel_rules_apple//apple:ios.bzl", "ios_application")

licenses(["notice"])

objc_library(
    name = "Main",
    testonly = 1,
    srcs = ["main.m"],
)	

# Default test host for unit tests.	
ios_application(
    name = "test_host",
    testonly = 1,
    bundle_id = "com.google.material.foundation.testing.TestHost",
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = ["TestHost.plist"],
    launch_storyboard = "LaunchScreen.storyboard",
    minimum_os_version = "10.0",
    visibility = ["//visibility:public"],
    deps = [":Main"],
)

build_test(
    name = "BuildTest",
    targets = [
        ":test_host",
    ],
)
